controller:
  workspace: /home/tubular/workspace
  # TODO git credentials

pipelines:
  myPipelines:
    repo: "git@github.com:alagyn/tubular-tests"
    # default-branch: main
    paths:
      - .
      - piplines
      - tests
      - other

nodes:
  myserver:
    port: 8000
    tags:
      - windows
      - gpu
  myotherserver:
    host: actualhostname
    port: 8008
    tags:
      - linux
      - whatever
