controller:

# TODO git credentials

pipelines:
  - mypipelinerepo:
    - repo: "git@github.com:alagyn/tubular"
    - default-branch: main
    - paths:
      - piplines
      - tests
      - other

nodes:
  - myserver:
    - port: 8000
    - tags:
      - windows
      - gpu
  - myotherserver:
    - host: actualhostname
    - port: 8008
    - tags:
      - linux
      - whatever
